apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  template:
    spec:
      containers:
        - name: sample-app
          image: ${{ secrets.AWS_REGISTRY_URL }}:${{ github.sha }}
