apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${{ secrets.AWS_REGISTRY_URL }}
  newName: ${{ secrets.AWS_REGISTRY_URL }}
  newTag: ${{ github.sha }}
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml
